<h1>Capstone 2 - NHL Salaries: 02_data_wrangling

<h2>Import Libraries

In [2]:
import pandas as pd
import numpy as np
import glob
import ydata_profiling

<h2>Load Data

Data was gathered from two sources.  
1. Salary information was scraped from www.capfriendly.com for the 2023-24 season.  It also includes player performance statistics and advanced metrics for player performance.  
<br>**Note:** capfriendly.com was recently purchased and will reportedly be shut down on or after July 5, 2024. https://puckpedia.com/ is the current best alternative source of salary cap information.  <br>
<br>
2. Official player performance statistics from www.nhl.com

**Load capfriendly.com**  
Data includes all players with an NHL contract in the 2023-34 season reguardless of whether they played a game or not

Data Reference: https://www.capfriendly.com/browse/active/2025/salary?stats-season=2024&display=signing-team,country,weight,height,draft,waivers-exempt,signing-status,expiry-year,performance-bonus,signing-bonus,caphit-percent,aav,length,minors-salary,base-salary,skater-individual-advanced-stats,skater-on-ice-advanced-stats,goalie-advanced-stats,arbitration-eligible,type,signing-age,signing-date,arbitration,extension

In [5]:
capfriendly = pd.read_csv(r'/Users/ness/Desktop/Springboard/Projects/-Capstone 2/NHL Salaries/data/23_24_capfriendly_extended_data.csv')
capfriendly.shape

(1571, 58)

**Load and combine NHL.com data**  
Data include only includes skaters (goalies excluded) who played in at least one game in the NHL during the 2023-24 season

In [6]:
# specifying the path to .xlsx files
path = "/Users/ness/Desktop/Springboard/Projects/-Capstone 2/NHL Salaries/data/"
 
# .xlsx files in the path
file_list = glob.glob(path + "/*.xlsx")
 
# list of excel files we want to merge.
excl_list = []
 
for file in file_list:
    excl_list.append(pd.read_excel(file))
 
# concatenate all DataFrames in the list
nhl_official_merged = pd.concat(excl_list, ignore_index=True)

**Export merged NHL.com data to .csv**

In [4]:
#nhl_official_merged.to_csv('/Users/ness/Desktop/Springboard/Projects/-Capstone 2/NHL Salaries/data/nhl_official_merged.csv', index=False)

**Rename nhl_official_merged for ease of use**

In [7]:
nhl = nhl_official_merged

nhl_official_merged.shape == nhl.shape

True

<h2>Data

**View and correct data types for both datasets**

In [15]:
capfriendly['TEAM']=capfriendly['TEAM'].astype(str)

In [16]:
capfriendly['TEAM'].dtypes

dtype('O')

features seperated by type (to be changed to):
https://docs.google.com/document/d/1F8UDKo5p10ED4UygCGKGzrnNQBuGPRt0FqkQwN16b9M/edit?usp=sharing

In [31]:
#to_string = ['PLAYER', 'TEAM', 'COUNTRY', 'POS', 'HANDED', 'SIGNING TEAM', 'CLAUSE', 'SIGNING', 'EXPIRY']
#capfriendly[['PLAYER', 'TEAM', 'COUNTRY', 'POS', 'HANDED', 'SIGNING TEAM', 'CLAUSE', 'SIGNING', 'EXPIRY']] = capfriendly[['PLAYER', 'TEAM', 'COUNTRY', 'POS', 'HANDED', 'SIGNING TEAM', 'CLAUSE', 'SIGNING', 'EXPIRY']].astype('str')
#capfriendly.dtypes

capfriendly['TEAM'] = capfriendly['TEAM'].astype('str')

In [32]:
capfriendly['TEAM'].dtype

dtype('O')

In [9]:
capfriendly.columns

Index(['PLAYER', 'TEAM', 'AGE', 'COUNTRY', 'WEIGHT', 'HEIGHT', 'POS', 'HANDED',
       'GP', 'G', 'A', 'P', 'P/GP', '+/-', 'Sh', 'Sh%', 'TOI', 'ixG', 'iSh',
       'iCF', 'iFF', 'ixG60', 'iSh60', 'iCF60', 'iFF60', 'SF', 'SA', 'SF%',
       'CF', 'CA', 'CF%', 'FF', 'FA', 'FF%', 'xGF', 'xGA', 'xGF%', 'W', 'L',
       'SO', 'GAA', 'Sv%', 'GA60', 'xGA60', 'GSAx60', 'SIGNING TEAM',
       'EXTENSION', 'SIGNING DATE', 'SIGNING AGE', 'CLAUSE', 'LENGTH',
       'SIGNING', 'EXPIRY', 'EXP. YEAR', 'CAP HIT', 'CAP HIT %', 'AAV',
       'SALARY'],
      dtype='object')

In [10]:
pd.unique(capfriendly['EXTENSION'])

array(['âœ”', nan], dtype=object)

## Follow up:

In [11]:
#remove $ change to int
pd.unique(capfriendly['SALARY'])

array(['$16,500,000', '$11,000,000', '$7,975,000', '$11,500,000',
       '$13,000,000', '$7,950,000', '$8,025,000', '$8,500,000',
       '$10,500,000', '$12,000,000', '$7,000,000', '$10,000,000',
       '$8,450,000', '$9,750,000', '$12,500,000', '$6,500,000',
       '$11,250,000', '$9,000,000', '$9,500,000', '$10,400,000',
       '$9,150,000', '$12,600,000', '$12,300,000', '$9,100,000',
       '$3,000,000', '$11,050,000', '$8,000,000', '$6,025,000',
       '$5,000,000', '$7,500,000', '$6,000,000', '$8,250,000',
       '$8,125,000', '$1,000,000', '$9,975,000', '$8,600,000',
       '$7,750,000', '$10,250,000', '$7,142,858', '$7,100,000',
       '$7,250,000', '$8,950,000', '$4,500,000', '$8,400,000',
       '$6,650,000', '$7,900,000', '$6,400,000', '$6,250,000',
       '$6,150,000', '$7,200,000', '$5,600,000', '$6,900,000',
       '$4,950,000', '$5,275,000', '$5,825,000', '$5,800,000',
       '$5,750,000', '$4,000,000', '$3,750,000', '$5,500,000',
       '$6,750,000', '$7,650,000', '$5,875,000', '$5,350,000',
       '$6,800,000', '$5,300,000', '$5,250,000', '$5,400,000',
       '$5,200,000', '$6,760,000', '$6,100,000', '$5,100,000',
       '$4,750,000', '$4,250,000', '$3,500,000', '$5,900,000',
       '$4,850,000', '$5,150,000', '$4,550,000', '$4,800,000',
       '$5,725,000', '$6,350,000', '$4,600,000', '$4,285,716',
       '$4,150,000', '$4,125,000', '$3,600,000', '$5,700,000',
       '$4,025,175', '$4,025,000', '$4,100,000', '$4,400,000',
       '$4,479,000', '$3,900,000', '$3,098,000', '$3,080,000',
       '$4,300,000', '$3,650,000', '$3,550,000', '$4,200,000',
       '$3,187,500', '$3,475,000', '$3,275,000', '$3,700,000',
       '$3,400,000', '$3,333,334', '$3,250,000', '$3,200,000',
       '$3,185,000', '$3,300,000', '$3,100,000', '$3,875,000',
       '$2,700,000', '$3,450,000', '$2,750,000', '$3,225,000',
       '$2,950,000', '$2,900,000', '$2,500,000', '$3,150,000',
       '$3,045,000', '$3,350,000', '$2,625,000', '$2,600,000',
       '$2,300,000', '$2,450,000', '$2,400,000', '$2,200,000',
       '$2,000,000', '$1,482,450', '$2,250,000', '$1,950,000',
       '$2,100,000', '$1,800,000', '$1,375,000', '$1,750,000',
       '$1,985,000', '$2,350,000', '$1,900,000', '$2,150,000',
       '$1,700,000', '$2,130,000', '$1,675,000', '$1,600,000',
       '$1,599,999', '$2,050,000', '$1,500,000', '$1,400,000',
       '$1,450,000', '$1,300,000', '$1,350,000', '$1,250,000',
       '$1,100,000', '$1,225,000', '$1,200,000', '$1,150,000',
       '$1,125,000', '$1,050,000', '$900,000', '$975,000', '$925,000',
       '$950,000', '$0', '$895,000', '$920,000', '$870,000', '$867,500',
       '$892,500', '$832,500', '$800,000', '$885,000', '$875,000',
       '$874,125', '$825,000', '$865,000', '$862,500', '$890,000',
       '$860,000', '$857,500', '$858,000', '$855,000', '$852,000',
       '$850,000', '$861,111', '$775,000', '$866,667', '$847,500',
       '$845,000', '$852,500', '$840,000', '$837,500', '$835,000',
       '$830,000', '$795,000', '$810,000', '$815,000', '$820,000',
       '$785,000', '$805,000', '$790,000', '$787,500', '$776,665'],
      dtype=object)

In [12]:
#remove $ change to int
pd.unique(capfriendly['AAV'])

array(['$12,600,000', '$12,500,000', '$11,642,857', '$11,640,250',
       '$11,500,000', '$11,250,000', '$11,000,000', '$10,903,000',
       '$10,500,000', '$10,000,000', '$9,850,000', '$9,750,000',
       '$9,583,333', '$9,500,000', '$9,250,000', '$9,200,000',
       '$9,150,000', '$9,059,000', '$9,000,000', '$8,800,000',
       '$8,700,000', '$8,500,000', '$8,460,250', '$8,450,000',
       '$8,350,000', '$8,250,000', '$8,205,714', '$8,137,500',
       '$8,125,000', '$8,000,000', '$7,950,000', '$7,875,000',
       '$7,857,143', '$7,850,000', '$7,800,000', '$7,750,000',
       '$7,575,000', '$7,500,000', '$7,350,000', '$7,250,000',
       '$7,150,000', '$7,142,857', '$7,100,000', '$7,000,000',
       '$6,962,366', '$6,875,000', '$6,750,000', '$6,650,000',
       '$6,500,000', '$6,400,000', '$6,250,000', '$6,166,667',
       '$6,150,000', '$6,125,000', '$6,100,000', '$6,000,000',
       '$5,950,000', '$5,900,000', '$5,875,000', '$5,850,000',
       '$5,825,000', '$5,800,000', '$5,750,000', '$5,700,000',
       '$5,666,667', '$5,625,000', '$5,500,000', '$5,400,000',
       '$5,375,000', '$5,350,000', '$5,300,000', '$5,291,667',
       '$5,250,000', '$5,200,000', '$5,166,667', '$5,166,666',
       '$5,125,000', '$5,100,000', '$5,000,000', '$4,975,000',
       '$4,950,000', '$4,900,000', '$4,875,000', '$4,850,000',
       '$4,820,000', '$4,750,000', '$4,725,000', '$4,600,000',
       '$4,550,000', '$4,500,000', '$4,450,000', '$4,437,500',
       '$4,425,000', '$4,400,000', '$4,300,000', '$4,285,714',
       '$4,250,000', '$4,200,000', '$4,166,667', '$4,150,000',
       '$4,125,000', '$4,100,000', '$4,050,000', '$4,025,175',
       '$4,025,000', '$4,000,000', '$3,979,000', '$3,900,000',
       '$3,872,000', '$3,850,000', '$3,800,000', '$3,750,000',
       '$3,687,500', '$3,650,000', '$3,641,667', '$3,550,000',
       '$3,500,000', '$3,475,000', '$3,437,500', '$3,425,000',
       '$3,400,000', '$3,362,500', '$3,333,333', '$3,275,000',
       '$3,250,000', '$3,200,000', '$3,185,000', '$3,150,000',
       '$3,125,000', '$3,100,000', '$3,000,000', '$2,950,000',
       '$2,900,000', '$2,857,143', '$2,850,000', '$2,750,000',
       '$2,725,000', '$2,700,000', '$2,675,000', '$2,666,667',
       '$2,665,000', '$2,650,000', '$2,625,000', '$2,600,000',
       '$2,500,000', '$2,450,000', '$2,400,000', '$2,375,000',
       '$2,350,000', '$2,333,333', '$2,325,000', '$2,300,000',
       '$2,294,150', '$2,250,000', '$2,200,000', '$2,166,667',
       '$2,100,000', '$2,062,500', '$2,000,000', '$1,950,000',
       '$1,900,000', '$1,850,000', '$1,800,000', '$1,775,000',
       '$1,750,000', '$1,700,000', '$1,675,000', '$1,600,000',
       '$1,599,999', '$1,525,000', '$1,500,000', '$1,460,000',
       '$1,450,000', '$1,400,000', '$1,350,000', '$1,300,000',
       '$1,295,000', '$1,275,000', '$1,250,000', '$1,225,000',
       '$1,200,000', '$1,150,000', '$1,137,500', '$1,125,000',
       '$1,100,000', '$1,050,000', '$1,000,000', '$987,500', '$975,000',
       '$962,500', '$950,000', '$1,550,000', '$1,033,333', '$1,366,667',
       '$2,116,667', '$1,425,000', '$1,733,333', '$1,333,333',
       '$1,283,333', '$935,833', '$1,158,333', '$925,000', '$1,167,500',
       '$1,337,500', '$1,633,333', '$1,562,500', '$1,491,667',
       '$1,441,667', '$1,066,667', '$1,243,750', '$1,387,500',
       '$1,208,333', '$1,566,667', '$1,008,333', '$1,325,000',
       '$1,918,333', '$1,418,333', '$918,333', '$4,168,333', '$1,168,333',
       '$3,980,833', '$1,410,000', '$1,393,333', '$1,685,000',
       '$1,701,667', '$1,160,833', '$1,668,333', '$1,031,250', '$900,000',
       '$1,139,367', '$894,167', '$1,294,167', '$3,544,167', '$1,394,167',
       '$1,744,167', '$1,419,167', '$1,000,417', '$1,035,833',
       '$1,627,500', '$3,394,167', '$2,444,167', '$890,000', '$885,000',
       '$875,000', '$902,500', '$874,125', '$879,167', '$870,000',
       '$1,523,333', '$863,333', '$1,105,833', '$1,005,000', '$1,275,833',
       '$1,713,333', '$934,167', '$1,034,167', '$1,075,833', '$1,288,333',
       '$1,313,333', '$1,596,667', '$915,833', '$860,000', '$859,167',
       '$858,333', '$858,000', '$857,500', '$910,833', '$903,333',
       '$856,667', '$855,000', '$852,500', '$851,683', '$851,667',
       '$850,000', '$875,002', '$849,667', '$847,500', '$846,667',
       '$926,667', '$893,333', '$845,833', '$845,000', '$871,667',
       '$844,167', '$843,333', '$842,500', '$841,667', '$840,000',
       '$838,750', '$838,333', '$837,500', '$836,667', '$881,667',
       '$835,000', '$834,167', '$832,500', '$831,667', '$850,556',
       '$830,000', '$829,444', '$828,333', '$878,333', '$826,667',
       '$826,111', '$896,667', '$880,000', '$825,000', '$854,167',
       '$833,333', '$821,667', '$919,167', '$820,000', '$818,333',
       '$817,778', '$817,500', '$816,667', '$813,333', '$812,500',
       '$810,000', '$809,444', '$807,500', '$805,000', '$802,500',
       '$801,667', '$800,556', '$800,000', '$796,667', '$796,111',
       '$842,222', '$795,556', '$793,333', '$791,667', '$790,000',
       '$905,000', '$888,333', '$787,500', '$785,000', '$784,722',
       '$776,667', '$776,665', '$775,000', '$766,667', '$762,500',
       '$758,333'], dtype=object)

In [13]:
#remove % change to float
pd.unique(capfriendly['CAP HIT %'])

array(['15.3%', '16.7%', '14.3%', '14.6%', '14.5%', '13.6%', '13.8%',
       '13.4%', '14.0%', '12.7%', '12.3%', '13.3%', '12.4%', '11.8%',
       '11.9%', '11.7%', '13.0%', '11.5%', '11.3%', '11.1%', '11.0%',
       '10.5%', '10.8%', '10.3%', '10.4%', '10.2%', '11.6%', '10.1%',
       '10.0%', '9.8%', '9.7%', '10.7%', '9.6%', '9.4%', '9.5%', '13.1%',
       '9.3%', '9.2%', '9.0%', '8.8%', '8.9%', '8.7%', '8.6%', '8.5%',
       '8.4%', '8.3%', '8.1%', '8.0%', '7.9%', '7.5%', '7.7%', '7.6%',
       '7.8%', '7.4%', '7.3%', '7.2%', '7.1%', '7.0%', '6.9%', '6.8%',
       '6.7%', '6.6%', '6.4%', '6.3%', '6.5%', '6.2%', '6.1%', '6.0%',
       '5.9%', '5.8%', '5.6%', '5.5%', '5.4%', '5.2%', '5.7%', '5.1%',
       '5.0%', '4.9%', '4.8%', '4.7%', '4.6%', '4.5%', '4.4%', '4.3%',
       '4.2%', '4.1%', '4.0%', '3.9%', '3.8%', '3.7%', '3.6%', '3.5%',
       '3.3%', '3.4%', '3.2%', '3.1%', '3.0%', '2.9%', '2.8%', '2.7%',
       '2.6%', '2.5%', '2.4%', '2.3%', '2.2%', '2.1%', '2.0%', '1.9%',
       '1.8%', '1.7%', '1.6%', '1.5%', '1.4%', '1.3%', '1.2%', '1.1%',
       '1.0%', '0.9%'], dtype=object)

In [14]:
#remove $ change to int
pd.unique(capfriendly['CAP HIT'])

array(['$12,600,000', '$12,500,000', '$11,642,857', '$11,640,250',
       '$11,500,000', '$11,250,000', '$11,000,000', '$10,903,000',
       '$10,500,000', '$10,000,000', '$9,850,000', '$9,750,000',
       '$9,583,333', '$9,500,000', '$9,250,000', '$9,200,000',
       '$9,150,000', '$9,059,000', '$9,000,000', '$8,800,000',
       '$8,700,000', '$8,500,000', '$8,460,250', '$8,450,000',
       '$8,350,000', '$8,250,000', '$8,205,714', '$8,137,500',
       '$8,125,000', '$8,000,000', '$7,950,000', '$7,875,000',
       '$7,857,143', '$7,850,000', '$7,800,000', '$7,750,000',
       '$7,575,000', '$7,500,000', '$7,350,000', '$7,250,000',
       '$7,150,000', '$7,142,857', '$7,100,000', '$7,000,000',
       '$6,962,366', '$6,875,000', '$6,750,000', '$6,650,000',
       '$6,500,000', '$6,400,000', '$6,250,000', '$6,166,667',
       '$6,150,000', '$6,125,000', '$6,100,000', '$6,000,000',
       '$5,950,000', '$5,900,000', '$5,875,000', '$5,850,000',
       '$5,825,000', '$5,800,000', '$5,750,000', '$5,700,000',
       '$5,666,667', '$5,625,000', '$5,500,000', '$5,400,000',
       '$5,375,000', '$5,350,000', '$5,300,000', '$5,291,667',
       '$5,250,000', '$5,200,000', '$5,166,667', '$5,166,666',
       '$5,125,000', '$5,100,000', '$5,000,000', '$4,975,000',
       '$4,950,000', '$4,900,000', '$4,875,000', '$4,850,000',
       '$4,820,000', '$4,750,000', '$4,725,000', '$4,600,000',
       '$4,550,000', '$4,500,000', '$4,450,000', '$4,437,500',
       '$4,425,000', '$4,400,000', '$4,300,000', '$4,285,714',
       '$4,250,000', '$4,200,000', '$4,166,667', '$4,150,000',
       '$4,125,000', '$4,100,000', '$4,050,000', '$4,025,175',
       '$4,025,000', '$4,000,000', '$3,979,000', '$3,900,000',
       '$3,872,000', '$3,850,000', '$3,800,000', '$3,750,000',
       '$3,687,500', '$3,650,000', '$3,641,667', '$3,550,000',
       '$3,500,000', '$3,475,000', '$3,437,500', '$3,425,000',
       '$3,400,000', '$3,362,500', '$3,333,333', '$3,275,000',
       '$3,250,000', '$3,200,000', '$3,185,000', '$3,150,000',
       '$3,125,000', '$3,100,000', '$3,000,000', '$2,950,000',
       '$2,900,000', '$2,857,143', '$2,850,000', '$2,750,000',
       '$2,725,000', '$2,700,000', '$2,675,000', '$2,666,667',
       '$2,665,000', '$2,650,000', '$2,625,000', '$2,600,000',
       '$2,500,000', '$2,450,000', '$2,400,000', '$2,375,000',
       '$2,350,000', '$2,333,333', '$2,325,000', '$2,300,000',
       '$2,294,150', '$2,250,000', '$2,200,000', '$2,166,667',
       '$2,100,000', '$2,062,500', '$2,000,000', '$1,985,000',
       '$1,950,000', '$1,900,000', '$1,850,000', '$1,800,000',
       '$1,775,000', '$1,750,000', '$1,700,000', '$1,675,000',
       '$1,600,000', '$1,599,999', '$1,525,000', '$1,500,000',
       '$1,460,000', '$1,450,000', '$1,400,000', '$1,350,000',
       '$1,300,000', '$1,295,000', '$1,275,000', '$1,250,000',
       '$1,225,000', '$1,200,000', '$1,150,000', '$1,137,500',
       '$1,125,000', '$1,100,000', '$1,050,000', '$1,000,000', '$987,500',
       '$975,000', '$962,500', '$950,000', '$941,667', '$940,000',
       '$935,833', '$931,667', '$925,000', '$923,333', '$922,500',
       '$920,000', '$918,333', '$916,667', '$913,333', '$912,500',
       '$910,000', '$905,833', '$905,000', '$903,333', '$900,833',
       '$900,000', '$898,750', '$897,500', '$896,667', '$896,250',
       '$895,000', '$894,167', '$891,667', '$890,000', '$886,667',
       '$885,000', '$883,750', '$882,500', '$878,333', '$875,833',
       '$875,000', '$874,125', '$870,833', '$870,000', '$867,500',
       '$865,000', '$864,167', '$863,333', '$862,500', '$861,667',
       '$860,000', '$859,167', '$858,333', '$858,000', '$857,500',
       '$856,667', '$855,833', '$855,000', '$852,500', '$851,683',
       '$851,667', '$850,833', '$850,000', '$849,667', '$848,333',
       '$847,500', '$846,667', '$845,833', '$845,000', '$844,167',
       '$843,333', '$842,500', '$841,667', '$840,000', '$839,167',
       '$838,750', '$838,333', '$837,500', '$836,667', '$835,833',
       '$835,000', '$834,167', '$833,333', '$832,500', '$831,667',
       '$830,833', '$830,556', '$830,000', '$829,444', '$828,333',
       '$826,667', '$826,111', '$825,000', '$823,333', '$821,667',
       '$820,000', '$818,333', '$817,778', '$817,500', '$816,667',
       '$814,167', '$813,333', '$812,500', '$810,000', '$809,444',
       '$807,500', '$805,833', '$805,000', '$803,333', '$802,500',
       '$801,667', '$800,556', '$800,000', '$797,500', '$796,667',
       '$796,111', '$795,556', '$795,000', '$793,333', '$791,667',
       '$790,000', '$789,167', '$787,500', '$786,111', '$785,000',
       '$784,722', '$776,667', '$776,665', '$775,000', '$766,667',
       '$762,500', '$758,333'], dtype=object)

In [15]:
#simplify to year
pd.unique(capfriendly['SIGNING DATE'])

array(['Sep. 20, 2022', 'Jul. 5, 2017', 'Jul. 1, 2019', 'Feb. 5, 2019',
       'Jun. 17, 2019', 'Mar. 2, 2023', 'Jul. 1, 2018', 'Sep. 13, 2019',
       'Jul. 2, 2017', 'Aug. 4, 2022', 'Oct. 8, 2021', 'Jan. 16, 2016',
       'Oct. 3, 2017', 'Sep. 13, 2018', 'Jul. 13, 2022', 'Jul. 29, 2021',
       'Mar. 8, 2019', 'Jul. 27, 2021', 'Nov. 1, 2021', 'Jul. 23, 2021',
       'Jul. 15, 2016', 'Jul. 10, 2018', 'Jul. 28, 2021', 'Oct. 15, 2021',
       'Jul. 29, 2019', 'Jul. 22, 2022', 'Sep. 28, 2019', 'Aug. 6, 2021',
       'Jan. 14, 2020', 'Oct. 4, 2022', 'Oct. 29, 2019', 'Jun. 7, 2019',
       'Jul. 24, 2021', 'Sep. 21, 2021', 'Jun. 28, 2023', 'Oct. 12, 2020',
       'Jul. 1, 2012', 'Mar. 1, 2023', 'Oct. 10, 2021', 'Jun. 27, 2023',
       'Aug. 16, 2017', 'Jul. 9, 2022', 'Feb. 5, 2023', 'Jun. 29, 2016',
       'Jul. 17, 2021', 'Nov. 29, 2022', 'Sep. 7, 2022', 'Jul. 30, 2015',
       'Oct. 14, 2021', 'Mar. 16, 2022', 'Sep. 13, 2022', 'Jun. 25, 2018',
       'Jul. 19, 2019', 'Nov. 30, 2021', 'Sep. 2, 2022', 'Sep. 19, 2019',
       'Jul. 28, 2017', 'Nov. 22, 2016', 'Jul. 14, 2022', 'Jul. 9, 2023',
       'Jun. 15, 2023', 'Jul. 1, 2016', 'Oct. 12, 2021', 'Jun. 29, 2022',
       'Jul. 24, 2012', 'Jun. 5, 2023', 'Oct. 1, 2021', 'Aug. 26, 2021',
       'Oct. 6, 2022', 'Jul. 1, 2023', 'Sep. 14, 2019', 'Oct. 29, 2021',
       'Jul. 21, 2023', 'Oct. 18, 2019', 'Sep. 4, 2019', 'Aug. 30, 2022',
       'Jun. 18, 2019', 'Feb. 7, 2023', 'Jul. 1, 2017', 'Aug. 18, 2022',
       'Jan. 16, 2023', 'Aug. 2, 2023', 'Dec. 1, 2018', 'Sep. 26, 2015',
       'Sep. 12, 2019', 'Jul. 1, 2022', 'Sep. 24, 2019', 'Sep. 1, 2021',
       'Feb. 24, 2020', 'Mar. 20, 2022', 'Oct. 4, 2019', 'Oct. 9, 2020',
       'Aug. 11, 2021', 'Oct. 14, 2020', 'Aug. 4, 2018', 'Aug. 14, 2018',
       'Oct. 13, 2021', 'Oct. 7, 2022', 'Jun. 9, 2023', 'Oct. 13, 2022',
       'Sep. 25, 2020', 'Jul. 12, 2018', 'Jul. 11, 2022', 'Sep. 26, 2016',
       'Jul. 8, 2016', 'Jul. 12, 2022', 'Jul. 7, 2022', 'Mar. 11, 2021',
       'Sep. 22, 2021', 'Oct. 4, 2017', 'Sep. 15, 2020', 'Dec. 27, 2018',
       'May 23, 2019', 'Oct. 25, 2018', 'Jun. 24, 2019', 'Jun. 7, 2023',
       'Nov. 16, 2017', 'Mar. 30, 2019', 'Jul. 16, 2018', 'May 16, 2019',
       'Aug. 2, 2022', 'Jun. 23, 2017', 'Oct. 2, 2023', 'Nov. 3, 2020',
       'Aug. 9, 2021', 'Jun. 14, 2019', 'Sep. 16, 2019', 'Jan. 26, 2023',
       'Oct. 8, 2020', 'Jul. 8, 2022', 'Jul. 2, 2023', 'Jan. 21, 2019',
       'Jan. 6, 2021', 'Feb. 16, 2018', 'Jul. 12, 2017', 'Sep. 14, 2017',
       'Jul. 2, 2021', 'Mar. 1, 2019', 'Jul. 28, 2018', 'Nov. 27, 2019',
       'Aug. 10, 2021', 'Sep. 25, 2018', 'Jul. 27, 2018', 'Nov. 2, 2018',
       'May 21, 2022', 'Jun. 29, 2021', 'Mar. 10, 2022', 'Mar. 31, 2021',
       'Jul. 10, 2017', 'Sep. 2, 2021', 'Feb. 3, 2023', 'Jul. 27, 2023',
       'Mar. 8, 2022', 'Jan. 3, 2018', 'Jul. 31, 2019', 'Oct. 3, 2020',
       'Aug. 16, 2021', 'Sep. 3, 2021', 'Aug. 30, 2018', 'Jun. 30, 2023',
       'Oct. 7, 2017', 'Mar. 21, 2022', 'Oct. 19, 2018', 'Jan. 14, 2023',
       'Oct. 10, 2020', 'Jul. 21, 2021', 'Nov. 13, 2018', 'Dec. 21, 2022',
       'Jan. 8, 2020', 'Sep. 27, 2022', 'May 2, 2017', 'Aug. 9, 2018',
       'Mar. 29, 2023', 'Jul. 26, 2021', 'Aug. 31, 2021', 'Jan. 3, 2021',
       'Aug. 8, 2022', 'Oct. 12, 2022', 'Jul. 22, 2017', 'Dec. 15, 2022',
       'Feb. 15, 2023', 'Jul. 14, 2021', 'Oct. 27, 2020', 'Feb. 28, 2023',
       'Jan. 28, 2020', 'Aug. 1, 2017', 'Jun. 7, 2022', 'Dec. 14, 2021',
       'Jul. 17, 2023', 'Aug. 22, 2022', 'Jul. 21, 2022', 'Apr. 12, 2021',
       'Sep. 1, 2022', 'Oct. 6, 2020', 'Aug. 6, 2023', 'Aug. 24, 2023',
       'Jul. 11, 2023', 'Oct. 1, 2022', 'Jul. 31, 2023', 'Oct. 17, 2020',
       'Jul. 22, 2021', 'Jul. 23, 2023', 'Jan. 1, 2023', 'Sep. 16, 2020',
       'Aug. 1, 2023', 'Jul. 19, 2023', 'Jul. 19, 2022', 'Jul. 10, 2022',
       'Jul. 26, 2022', 'Apr. 16, 2020', 'Oct. 11, 2020', 'Apr. 16, 2021',
       'Apr. 8, 2021', 'Jun. 23, 2023', 'Mar. 21, 2021', 'Jan. 26, 2022',
       'Jan. 12, 2021', 'Oct. 7, 2020', 'Aug. 9, 2022', 'May 10, 2021',
       'Jul. 15, 2021', 'Mar. 11, 2023', 'Jan. 31, 2022', 'Feb. 16, 2023',
       'Jul. 28, 2022', 'Jun. 25, 2023', 'Jul. 23, 2019', 'Jan. 30, 2022',
       'Sep. 28, 2022', 'Jul. 18, 2022', 'Oct. 28, 2021', 'Nov. 28, 2023',
       'Jul. 31, 2021', 'Jul. 7, 2023', 'Jul. 4, 2023', 'Jul. 15, 2023',
       'Sep. 11, 2020', 'Aug. 14, 2021', 'Jul. 10, 2023', 'Jul. 6, 2022',
       'Dec. 19, 2022', 'May 9, 2022', 'Jun. 20, 2023', 'May 24, 2023',
       'Mar. 3, 2023', 'Aug. 23, 2023', 'Oct. 5, 2023', 'Oct. 10, 2022',
       'Mar. 3, 2020', 'Oct. 20, 2022', 'Aug. 7, 2022', 'Apr. 13, 2023',
       'Jul. 15, 2022', 'Sep. 6, 2023', 'Dec. 28, 2023', 'Nov. 23, 2022',
       'Mar. 30, 2022', 'May 2, 2023', 'Jun. 13, 2022', 'Mar. 12, 2022',
       'Feb. 4, 2023', 'Jul. 25, 2022', 'Jul. 5, 2022', 'Mar. 5, 2022',
       'Aug. 5, 2022', 'Oct. 3, 2021', 'Apr. 22, 2021', 'Sep. 15, 2022',
       'Jul. 24, 2023', 'Aug. 11, 2023', 'Jul. 30, 2023', 'Sep. 12, 2023',
       'Jan. 11, 2021', 'Feb. 10, 2023', 'Jul. 29, 2022', 'Aug. 30, 2021',
       'Jun. 27, 2022', 'Feb. 27, 2020', 'Sep. 29, 2022', 'Aug. 26, 2022',
       'Jul. 5, 2023', 'Apr. 25, 2021', 'Nov. 14, 2021', 'Jul. 16, 2023',
       'Apr. 11, 2023', 'Jan. 11, 2022', 'Apr. 29, 2022', 'May 16, 2022',
       'Jan. 2, 2023', 'Jul. 16, 2022', 'Jul. 3, 2023', 'Jun. 21, 2023',
       'Oct. 26, 2021', 'Feb. 9, 2023', 'Jun. 15, 2022', 'Aug. 19, 2023',
       'Feb. 8, 2022', 'Jun. 30, 2022', 'Jan. 24, 2023', 'Apr. 5, 2022',
       'May 10, 2023', 'Jun. 12, 2023', 'Feb. 25, 2022', 'Apr. 13, 2024',
       'Oct. 4, 2023', 'May 8, 2023', 'Mar. 20, 2023', 'Apr. 14, 2024',
       'Aug. 21, 2023', 'Apr. 15, 2024', 'Jul. 12, 2023', 'Mar. 22, 2023',
       'Mar. 31, 2023', 'Jul. 28, 2023', 'May 6, 2023', 'Jul. 14, 2023',
       'Sep. 21, 2023', 'May 3, 2023', 'Jul. 6, 2023', 'May 1, 2023',
       'Apr. 7, 2024', 'Apr. 12, 2024', 'Jul. 26, 2023', 'Apr. 4, 2024',
       'Aug. 10, 2023', 'Mar. 25, 2023', 'Apr. 27, 2021', 'Jun. 7, 2021',
       'Apr. 8, 2022', 'Jun. 6, 2022', 'Mar. 31, 2022', 'Apr. 9, 2023',
       'Mar. 7, 2023', 'May 30, 2021', 'Jun. 9, 2021', 'Aug. 18, 2021',
       'May 3, 2022', 'May 11, 2022', 'May 23, 2022', 'Apr. 30, 2022',
       'Mar. 26, 2023', 'May 20, 2021', 'Jul. 7, 2021', 'Mar. 23, 2022',
       'May 5, 2023', 'Apr. 10, 2022', 'Mar. 15, 2022', 'Apr. 9, 2022',
       'Mar. 22, 2021', 'Mar. 27, 2022', 'Apr. 1, 2022', 'Apr. 26, 2022',
       'May 7, 2022', 'Mar. 13, 2023', 'Apr. 10, 2023', 'Apr. 15, 2023',
       'Feb. 28, 2024', 'Jul. 8, 2023', 'Mar. 15, 2023', 'Apr. 8, 2023',
       'May 27, 2023', 'Mar. 1, 2021', 'Mar. 17, 2023', 'May 4, 2023',
       'Apr. 11, 2024', 'Mar. 27, 2023', 'Mar. 3, 2021', 'Apr. 13, 2021',
       'Jun. 3, 2021', 'Jun. 11, 2023', 'Apr. 28, 2023', 'Apr. 4, 2023',
       'Aug. 17, 2022', 'Aug. 10, 2022', 'Apr. 16, 2022', 'Mar. 23, 2023',
       'Apr. 12, 2023', 'Apr. 2, 2024', 'Mar. 14, 2023', 'Sep. 26, 2023',
       'Mar. 10, 2024', 'Mar. 6, 2023', 'Aug. 16, 2023', 'Mar. 28, 2023',
       'Apr. 10, 2024', 'Aug. 3, 2022', 'Jul. 13, 2023', 'Jun. 13, 2023',
       'Aug. 18, 2023', 'Apr. 22, 2022', 'Mar. 30, 2021', 'Apr. 4, 2022',
       'Feb. 7, 2022', 'May 5, 2022', 'Apr. 3, 2023', 'Sep. 5, 2023',
       'Dec. 14, 2023', 'Jul. 25, 2023', 'Oct. 10, 2023', 'Dec. 1, 2021',
       'Oct. 16, 2020', 'Dec. 28, 2020', 'May 31, 2022', 'Sep. 28, 2021',
       'Apr. 24, 2022', 'Jun. 3, 2020', 'Nov. 9, 2020', 'Aug. 13, 2021',
       'Apr. 27, 2022', 'Mar. 11, 2020', 'Apr. 19, 2021', 'Mar. 23, 2020',
       'Dec. 24, 2020', 'Nov. 25, 2022', 'Dec. 1, 2022', 'Sep. 8, 2022',
       'Apr. 5, 2023', 'May 25, 2023', 'Mar. 29, 2022', 'Jun. 9, 2022',
       'May 26, 2022', 'May 17, 2022', 'Mar. 14, 2022', 'Mar. 8, 2023',
       'May 26, 2021', 'Apr. 18, 2024', 'Aug. 9, 2023', 'Apr. 22, 2023',
       'Apr. 29, 2024', 'Oct. 5, 2022', 'Nov. 17, 2023', 'Mar. 30, 2023',
       'Apr. 18, 2023', 'Apr. 16, 2023', 'Apr. 19, 2023', 'Sep. 13, 2023',
       'Mar. 10, 2023', 'Apr. 20, 2021', 'Apr. 27, 2023', 'Sep. 24, 2023',
       'Apr. 14, 2023', 'May 31, 2023', 'Mar. 19, 2023', 'Mar. 21, 2023',
       'Apr. 7, 2023', 'May 19, 2023', 'May 11, 2023', 'Mar. 9, 2023',
       'Jul. 7, 2019', 'Sep. 23, 2019', 'Dec. 31, 2020', 'Nov. 5, 2020',
       'Aug. 19, 2021', 'Jun. 25, 2019', 'Jul. 12, 2019', 'Aug. 24, 2021',
       'Jul. 14, 2019', 'Sep. 18, 2019', 'Oct. 21, 2019', 'Nov. 16, 2020',
       'Aug. 25, 2021', 'Jul. 15, 2019', 'Nov. 16, 2019', 'Sep. 22, 2019',
       'Oct. 20, 2020', 'Dec. 29, 2020', 'Aug. 12, 2021', 'Jul. 4, 2019',
       'Oct. 23, 2020', 'Dec. 28, 2021', 'Mar. 18, 2023', 'Jun. 1, 2021',
       'Oct. 19, 2022', 'Nov. 14, 2022', 'Oct. 25, 2023', 'Mar. 1, 2022',
       'May 4, 2022', 'Apr. 21, 2022', 'Mar. 16, 2023', 'Nov. 29, 2023',
       'Aug. 20, 2022', 'Oct. 14, 2022', 'May 13, 2022', 'Jun. 11, 2021',
       'May 6, 2021', 'Apr. 8, 2020', 'May 2, 2022', 'Dec. 7, 2023',
       'May 6, 2022', 'May 25, 2022', 'Jun. 10, 2022', 'Dec. 31, 2023',
       'Mar. 28, 2022', 'Jun. 1, 2022', 'Dec. 2, 2021', 'Dec. 29, 2023',
       'Oct. 8, 2023', 'Dec. 22, 2023', 'May 15, 2023', 'Mar. 4, 2021',
       'May 28, 2021', 'May 1, 2021', 'May 17, 2021', 'Mar. 19, 2021',
       'May 5, 2021', 'May 23, 2021', 'Apr. 21, 2021', 'Nov. 2, 2021',
       'Mar. 29, 2021', 'Apr. 9, 2021', 'Dec. 6, 2021', 'Aug. 19, 2022',
       'May 30, 2022', 'Sep. 25, 2023', 'Mar. 19, 2022', 'May 12, 2021',
       'Jun. 4, 2021', 'May 25, 2021', 'Sep. 24, 2021', 'Dec. 31, 2022',
       'Apr. 11, 2022', 'Nov. 26, 2023', 'Apr. 13, 2022', 'Mar. 2, 2022',
       'Jun. 1, 2023', 'Dec. 30, 2020', 'Mar. 17, 2021', 'Dec. 23, 2022',
       'Mar. 22, 2022', 'Apr. 2, 2023', 'Aug. 31, 2022', 'May 22, 2022',
       'May 20, 2022', 'Apr. 18, 2022', 'Aug. 1, 2022', 'May 12, 2022',
       'Oct. 27, 2022', 'Feb. 18, 2022', 'Dec. 27, 2022', 'Dec. 30, 2022',
       'Dec. 17, 2022', 'Oct. 30, 2022', 'Dec. 10, 2022', 'Dec. 23, 2021',
       'Mar. 15, 2021', 'Oct. 4, 2021', 'Apr. 6, 2021', 'Sep. 30, 2022',
       'May 18, 2021', 'May 19, 2021', 'May 27, 2021', 'May 13, 2021',
       'Sep. 26, 2021', 'Jan. 26, 2024', 'Sep. 29, 2021', 'May 31, 2021',
       'Aug. 22, 2023', 'Sep. 19, 2023', 'Sep. 16, 2021', 'Aug. 25, 2022',
       'Apr. 24, 2023', 'May 14, 2021', 'Sep. 6, 2021', 'Mar. 17, 2022',
       'Apr. 10, 2020', 'Jun. 14, 2021', 'Sep. 30, 2021', 'Jun. 5, 2020',
       'Dec. 13, 2020', 'Nov. 4, 2021', 'Sep. 23, 2022', 'Dec. 18, 2020',
       'Sep. 25, 2021', 'Nov. 6, 2022', 'Aug. 1, 2019', 'Mar. 11, 2022',
       'Oct. 5, 2021', 'May 1, 2020', 'Apr. 3, 2021', 'Jun. 2, 2023',
       'Feb. 15, 2024', 'Jun. 16, 2023', 'Oct. 16, 2023', 'Mar. 10, 2020',
       'Dec. 10, 2021', 'Aug. 15, 2021', 'Nov. 11, 2021', 'Oct. 11, 2021',
       'Oct. 2, 2021', 'Dec. 20, 2021', 'Feb. 8, 2023', 'Sep. 9, 2023',
       'Jan. 4, 2023', 'Feb. 4, 2024', 'Oct. 6, 2023', 'Jun. 22, 2023',
       'Aug. 29, 2022', 'Nov. 25, 2021', 'Feb. 19, 2022', 'Jun. 22, 2022',
       'Aug. 7, 2023', 'Oct. 8, 2019', 'Dec. 12, 2020', 'Oct. 2, 2022',
       'Oct. 13, 2020', 'Dec. 9, 2020', 'May 24, 2021', 'Dec. 30, 2019',
       'Jul. 10, 2019', 'Oct. 19, 2019', 'Oct. 24, 2019', 'Sep. 20, 2019',
       'Jul. 2, 2019', 'Dec. 21, 2019', 'Jun. 14, 2022', 'Aug. 23, 2019',
       'Mar. 9, 2022', 'Oct. 9, 2023', 'Jun. 23, 2022', 'Oct. 7, 2023',
       'Oct. 31, 2023', 'Jun. 14, 2023', 'Jun. 24, 2023', 'Nov. 12, 2023',
       'Jan. 22, 2024', 'Mar. 8, 2024', 'Jun. 26, 2023', 'Nov. 21, 2023',
       'Nov. 25, 2023', 'Jun. 29, 2023', 'Sep. 17, 2023', 'Nov. 27, 2023',
       'Mar. 4, 2024', 'Mar. 12, 2023', 'Feb. 18, 2024', 'Jun. 20, 2022',
       'Jun. 6, 2023', 'Aug. 28, 2023', 'Oct. 13, 2023', 'Mar. 5, 2024',
       'Aug. 13, 2022', 'May 19, 2022', 'May 30, 2023', 'Aug. 31, 2023',
       'Dec. 2, 2023', 'Mar. 6, 2024', 'Jul. 18, 2023', 'Mar. 6, 2022',
       'Feb. 6, 2023', 'Sep. 1, 2023', 'Sep. 20, 2023', 'Oct. 30, 2023',
       'Dec. 19, 2023', 'Mar. 7, 2024', 'Feb. 11, 2022', 'Jan. 21, 2022',
       'Mar. 7, 2022', 'Aug. 23, 2022', 'Feb. 28, 2022', 'Jun. 17, 2022',
       'Jul. 23, 2022', 'Sep. 21, 2022', 'Jun. 18, 2022', 'Feb. 23, 2023',
       'Mar. 3, 2022', 'Jul. 27, 2022', 'Jun. 21, 2022', 'Feb. 20, 2022',
       'Jul. 30, 2021'], dtype=object)

In [16]:
#change to boolean
pd.unique(capfriendly['EXTENSION'])

array(['âœ”', nan], dtype=object)

In [17]:
#change from MM:SS to something else
pd.unique(capfriendly['TOI'])

array(['22:48', '21:21', '20:07', '20:57', '24:16', '19:55', '25:47',
       '17:51', '21:16', '-', '17:25', '19:38', '19:39', '20:31', '16:32',
       '18:48', '24:27', '19:24', '19:13', '23:26', '25:29', '15:07',
       '21:40', '20:02', '24:50', '18:38', '22:54', '21:53', '14:33',
       '24:37', '15:59', '24:46', '21:34', '20:58', '17:36', '23:33',
       '15:13', '20:05', '20:10', '22:33', '19:44', '15:42', '20:41',
       '18:54', '19:41', '18:13', '19:37', '24:32', '17:14', '21:07', nan,
       '19:08', '20:29', '18:19', '25:53', '21:14', '19:29', '23:02',
       '13:38', '18:45', '21:30', '17:38', '17:53', '19:18', '24:48',
       '21:15', '18:02', '19:25', '24:41', '17:33', '17:49', '16:58',
       '17:18', '23:19', '20:51', '23:44', '23:05', '19:28', '19:14',
       '18:07', '19:43', '14:28', '17:13', '16:16', '18:25', '15:34',
       '18:17', '19:54', '22:09', '21:47', '18:36', '21:57', '23:51',
       '18:47', '23:17', '24:25', '17:46', '20:17', '13:47', '18:43',
       '21:02', '24:10', '22:55', '21:08', '18:31', '23:48', '19:06',
       '20:11', '18:35', '25:25', '18:53', '18:56', '15:52', '16:19',
       '23:22', '20:00', '18:05', '15:38', '16:48', '20:37', '20:49',
       '15:56', '19:10', '16:50', '20:28', '19:49', '16:52', '17:05',
       '20:16', '14:13', '21:27', '16:21', '17:26', '19:50', '14:53',
       '15:27', '16:02', '18:01', '19:30', '16:24', '16:10', '13:49',
       '20:55', '13:03', '19:02', '18:03', '12:07', '22:05', '19:11',
       '18:06', '19:34', '16:46', '16:41', '19:23', '15:32', '16:11',
       '17:57', '15:44', '16:45', '16:06', '21:43', '15:54', '15:47',
       '19:22', '16:30', '16:08', '18:10', '23:37', '14:32', '17:07',
       '25:33', '12:58', '14:15', '11:34', '19:46', '15:37', '11:37',
       '22:23', '21:01', '23:49', '13:43', '15:30', '18:28', '17:59',
       '18:23', '15:03', '15:40', '15:55', '19:45', '15:31', '16:36',
       '16:49', '20:30', '13:05', '16:57', '17:58', '20:33', '13:34',
       '19:05', '23:25', '22:40', '20:39', '15:33', '12:52', '22:21',
       '17:45', '22:56', '24:30', '14:57', '15:18', '13:22', '18:44',
       '22:59', '21:33', '20:20', '17:35', '18:20', '12:33', '20:14',
       '14:35', '16:40', '17:00', '16:14', '15:04', '19:20', '13:01',
       '16:33', '12:28', '12:30', '22:52', '20:01', '17:29', '12:56',
       '14:23', '17:44', '20:53', '17:15', '12:34', '15:39', '15:10',
       '17:21', '19:21', '15:46', '17:47', '18:41', '18:39', '15:19',
       '16:28', '16:03', '16:55', '15:22', '16:34', '16:23', '18:29',
       '15:23', '18:22', '15:11', '13:58', '11:04', '22:08', '12:01',
       '11:50', '11:56', '20:50', '13:20', '13:41', '13:44', '13:25',
       '13:56', '18:58', '19:48', '15:57', '12:36', '13:29', '12:29',
       '17:16', '11:09', '13:45', '18:33', '19:01', '13:10', '13:16',
       '15:15', '14:14', '15:49', '14:54', '10:54', '15:24', '14:27',
       '14:26', '14:48', '16:35', '15:53', '11:06', '10:35', '12:00',
       '14:39', '13:59', '14:56', '13:13', '14:40', '14:38', '14:20',
       '09:37', '11:52', '08:08', '14:34', '16:01', '16:31', '22:43',
       '11:49', '15:29', '22:37', '11:19', '12:37', '19:15', '12:27',
       '09:18', '11:59', '18:51', '14:59', '11:10', '15:08', '11:41',
       '10:51', '17:28', '10:29', '10:09', '08:06', '11:12', '10:56',
       '15:12', '12:03', '14:45', '12:31', '12:12', '12:46', '14:29',
       '17:04', '11:24', '12:11', '15:35', '13:48', '12:38', '11:16',
       '12:06', '08:11', '14:44', '08:47', '17:23', '11:53', '17:09',
       '12:23', '09:08', '13:30', '10:13', '13:46', '11:58', '12:50',
       '09:41', '11:48', '04:49', '14:16', '12:20', '15:48', '14:31',
       '17:56', '12:08', '19:47', '18:37', '13:32', '13:40', '10:48',
       '14:06', '16:07', '14:43', '12:35', '13:31', '12:02', '11:22',
       '12:16', '10:34', '23:13', '13:06', '08:17', '11:31', '10:37',
       '21:28', '13:52', '24:58', '13:27', '09:05', '19:51', '19:36',
       '14:30', '18:50', '03:55', '13:51', '15:01', '12:39', '11:15',
       '19:59', '13:00', '11:08', '12:40', '11:36', '10:11', '09:57',
       '13:09', '17:52', '11:45', '07:31', '21:09', '16:29', '08:35',
       '18:15', '13:35', '09:16', '11:38', '09:24', '09:35', '20:34',
       '07:00', '10:20', '16:47', '10:08', '14:09', '11:03', '07:17',
       '07:25', '09:28', '06:06', '09:48', '16:12', '13:23', '09:19',
       '13:08', '11:26', '15:16', '10:06', '13:19', '13:39', '07:47',
       '16:43', '16:59', '00:54', '13:42', '18:34', '06:47', '11:27',
       '14:11', '11:33', '09:21', '10:33', '11:23', '16:27', '15:41',
       '08:20', '13:14', '08:12', '12:13', '16:15', '06:48', '09:20',
       '06:26', '08:50', '08:24', '19:17', '07:43', '10:14', '06:45',
       '11:30', '14:41', '11:07', '18:11', '10:36', '13:57', '15:05',
       '08:07', '14:25', '05:37', '07:40', '08:31', '09:49', '14:37',
       '07:55', '10:55', '16:37', '14:12', '08:00', '14:46', '12:26',
       '07:48', '12:22', '09:11', '08:49', '10:05', '12:43', '09:04',
       '12:15', '09:32', '10:50', '12:41', '11:39', '09:40', '17:17',
       '12:59', '09:56', '13:53', '10:10', '07:15', '07:52', '10:03',
       '09:45', '18:32', '08:19', '10:12', '12:10', '06:42', '06:43',
       '14:55', '09:03', '09:31', '09:50', '10:58', '07:19', '05:35',
       '11:17', '10:52', '09:01', '05:09', '11:05', '12:47', '07:42',
       '17:43', '08:43', '08:40', '07:13', '03:05', '05:21', '08:22',
       '05:59', '07:58', '10:46', '08:05', '08:46', '12:05', '13:12',
       '10:31', '10:18', '06:23', '09:15', '14:05', '07:49', '13:04',
       '16:56', '07:06', '09:27', '13:15', '10:59', '09:43', '11:44',
       '11:02', '14:47', '07:27', '06:52', '02:03', '07:28', '10:45',
       '07:30', '06:28', '10:26', '12:17', '09:58', '10:01', '15:43',
       '07:35', '11:42', '11:51', '13:28', '05:38', '20:43', '08:26',
       '17:31', '10:40', '11:11', '11:28'], dtype=object)

In [18]:
#these dont have the same cap hit and AAV. explore why
capfriendly[capfriendly['CAP HIT'] != capfriendly['AAV']]

,PLAYER,TEAM,AGE,COUNTRY,WEIGHT,HEIGHT,POS,HANDED,GP,G,...,SIGNING AGE,CLAUSE,LENGTH,SIGNING,EXPIRY,EXP. YEAR,CAP HIT,CAP HIT %,AAV,SALARY
306,307. Joe Pavelski,DAL,38,United States,195,"5'11""",RW,Right,82,27,...,38,NMC,1,UFA,UFA,2024,"$3,500,000",4.2%,"$5,500,000","$3,500,000"
392,393. Kyle Okposo,FLA,35,United States,216,"6'0""",RW,Right,67,12,...,35,NaN,1,UFA,UFA,2024,"$2,500,000",3.0%,"$3,000,000","$2,500,000"
433,434. Max Pacioretty,WSH,34,United States,215,"6'2""",LW,Left,47,4,...,34,NMC,1,UFA,UFA,2024,"$2,000,000",2.4%,"$4,000,000","$2,000,000"
445,446. Sean Monahan,WPG,28,Canada,202,"6'2""","C, LW, RW",Left,83,26,...,28,NaN,1,UFA,UFA,2024,"$1,985,000",2.4%,"$2,000,000","$1,985,000"
547,548. Milan Lucic,BOS,35,Canada,231,"6'3""","LW, RW",Left,4,0,...,35,NMC,1,UFA,UFA,2024,"$1,000,000",1.2%,"$1,500,000","$1,000,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,1208. Artemi Kniazev,WPG,22,Russia,182,"5'10""",LD,Left,0,0,...,18,NaN,3,ELC,RFA,2024,"$789,167",1.0%,"$905,000","$775,000"
1208,1209. Kaedan Korczak,VGK,22,Canada,192,"6'3""",RD,Right,26,1,...,18,NaN,3,ELC,RFA,2024,"$789,167",1.0%,"$905,000","$775,000"
1221,1222. Arturs Silovs,VAN,22,Latvia,203,"6'4""",G,Left,4,-,...,18,NaN,3,ELC,RFA,2024,"$786,111",1.0%,"$796,111","$775,000"
1274,1275. Corey Perry,EDM,38,Canada,205,"6'3""",RW,Right,54,12,...,38,NaN,1,UFA,UFA,2024,"$775,000",0.9%,"$1,100,000","$775,000"
1320,1321. Connor Brown,EDM,29,Canada,186,"6'0""","RW, LW",Right,71,4,...,29,NaN,1,UFA,UFA,2024,"$775,000",0.9%,"$4,000,000","$775,000"

In [19]:
capfriendly.head()

,PLAYER,TEAM,AGE,COUNTRY,WEIGHT,HEIGHT,POS,HANDED,GP,G,...,SIGNING AGE,CLAUSE,LENGTH,SIGNING,EXPIRY,EXP. YEAR,CAP HIT,CAP HIT %,AAV,SALARY
0,1. Nathan MacKinnon,COL,27,Canada,200,"6'0""",C,Right,82,51,...,27,NMC,8,UFA,UFA,2031,"$12,600,000",15.3%,"$12,600,000","$16,500,000"
1,2. Connor McDavid,EDM,26,Canada,193,"6'1""",C,Left,76,32,...,21,NMC,8,RFA,UFA,2026,"$12,500,000",16.7%,"$12,500,000","$11,000,000"
2,3. Artemi Panarin,NYR,31,Russia,170,"5'11""",LW,Right,82,49,...,27,NMC,7,UFA,UFA,2026,"$11,642,857",14.3%,"$11,642,857","$11,000,000"
3,4. Auston Matthews,TOR,25,United States,215,"6'3""",C,Left,81,69,...,21,NMC,5,RFA,UFA,2024,"$11,640,250",14.6%,"$11,640,250","$7,975,000"
4,5. Erik Karlsson,PIT,33,Sweden,190,"6'0""",RD,Right,82,11,...,29,NMC,8,UFA,UFA,2027,"$11,500,000",14.5%,"$11,500,000","$11,500,000"

In [20]:
nhl.dtypes

Player     object
Season      int64
Team       object
S/C        object
Pos        object
GP          int64
G           int64
A           int64
P           int64
+/-         int64
PIM         int64
P/GP      float64
EVG         int64
EVP         int64
PPG         int64
PPP         int64
SHG         int64
SHP         int64
OTG         int64
GWG         int64
S           int64
S%         object
TOI/GP     object
FOW%       object
dtype: object

In [21]:
nhl.head()

,Player,Season,Team,S/C,Pos,GP,G,A,P,+/-,...,PPG,PPP,SHG,SHP,OTG,GWG,S,S%,TOI/GP,FOW%
0,Mikael Backlund,20232024,CGY,L,C,82,15,24,39,-4,...,2,3,1,2,0,2,209,7.2,19:14,50.3
1,Scott Laughton,20232024,PHI,L,C,82,13,26,39,-9,...,1,5,2,8,0,2,167,7.8,15:39,48.9
2,Evan Rodrigues,20232024,FLA,R,C,80,12,27,39,26,...,3,10,0,0,0,1,186,6.5,15:10,50
3,Gustav Forsling,20232024,FLA,L,D,79,10,29,39,56,...,1,2,0,0,1,1,160,6.3,22:09,--
4,Rasmus Andersson,20232024,CGY,R,D,78,9,30,39,-11,...,0,8,1,1,1,3,159,5.7,23:50,--

**Limit capfriendly.com data to only skaters**

In [ ]:
capfriendly = capfriendly[capfriendly['POS']!='G']
capfriendly.shape

**Use player names from NHL official data to filter capfriendly data**  
Limit capfriendly data to only players that played in the NHL during the 2023-24 season

In [ ]:
# player names from NHL offical data
names = nhl['Player'].to_list()
names
#filter cap friendly
#test = capfriendly[capfriendly['PLAYER'].isin(names)]
#test.shape
capfriendly.query('PLAYER in @names')

In [ ]:
pd.DataFrame.query?